export type ProductGridRow = {
  client_row_id: string;
  product_record_id: string;
  product_id: string;
  product_display_id: string;
  product_category: string;
  product_range: string;
  religion_use: string;
  product_name: string;
  site_english: string;
  site_mandarin: string;
  area_zone_block: string;
  section_block_wall: string;
  unit_lot_side: string;
  level_tier: string;
  product_type: string;
  size: string;
  position_type: string;
  as_need_price: string;
  pre_need_price: string;
  trust_account_and_facility_cost: string;
  back_wall: string;
  pre_total_price: string;
  active: boolean;
  remark: string;
  manual_group_id: string | null;
  manual_group_color: string | null;
  manual_group_position: string | null;
  is_new: boolean;
};
